### ISSUE TITLE
New Device Finder 7m.38

### ISSUE THREAD

**Issue by wasn-eu** [timlaing/modbus_local_gateway#1]
this is a file for the finder 7m.38 3phase Meter:

device:
  manufacturer: Finder
  model: 7M.38

entities:
  L1 Voltage:
    address: 2500
    title: L1 Voltage
    unit_of_measurement: V
    precision: 2
    float: True
    device_class: voltage
    state_class: measurement
    size: 2

  L2 Voltage:
    address: 2502
    title: L2 Voltage
    unit_of_measurement: V
    precision: 2
    float: True
    device_class: voltage
    state_class: measurement
    size: 2
    
  L3 Voltage:
    address: 2504
    title: L3 Voltage
    unit_of_measurement: V
    precision: 2
    float: True
    device_class: voltage
    state_class: measurement
    size: 2    
  
  L1 Current:
    address: 2516
    title: L1 Current
    unit_of_measurement: A
    precision: 2
    float: True
    device_class: current
    state_class: measurement
    size: 2  
    
  L2 Current:
    address: 2518
    title: L2 Current
    unit_of_measurement: A
    precision: 2
    float: True
    device_class: current
    state_class: measurement
    size: 2  

  L3 Current:
    address: 2520
    title: L3 Current
    unit_of_measurement: A
    precision: 2
    float: True
    device_class: current
    state_class: measurement
    size: 2  

  L1 active Power:
    address: 2530
    title: L1 active Power 
    unit_of_measurement: W
    precision: 2
    float: True
    device_class: power
    state_class: measurement
    size: 2  
    
  L2 active Power:
    address: 2532
    title: L2 active Power 
    unit_of_measurement: W
    precision: 2
    float: True
    device_class: power
    state_class: measurement
    size: 2  
    
  L3 active Power:
    address: 2534
    title: L3 active Power 
    unit_of_measurement: W
    precision: 2
    float: True
    device_class: power
    state_class: measurement
    size: 2  
    
  Total active Power:
    address: 2536
    title: Total active Power 
    unit_of_measurement: W
    precision: 2
    float: True
    device_class: power
    state_class: measurement
    size: 2  
    
  L1 apparent Power:
    address: 2546
    title: L1 apparent Power 
    unit_of_measurement: VA
    precision: 2
    float: True
    device_class: apparent_power
    state_class: measurement
    size: 2  

  L2 apparent Power:
    address: 2548
    title: L2 apparent Power 
    unit_of_measurement: VA
    precision: 2
    float: True
    device_class: apparent_power
    state_class: measurement
    size: 2  

  L3 apparent Power:
    address: 2550
    title: L3 apparent Power 
    unit_of_measurement: VA
    precision: 2
    float: True
    device_class: apparent_power
    state_class: measurement
    size: 2 
    
  Total apparent Power:
    address: 2552
    title: Total apparent Power 
    unit_of_measurement: VA
    precision: 2
    float: True
    device_class: apparent_power
    state_class: measurement
    size: 2  
    
  L1 reactive Power:
    address: 2538
    title: L1 reactive Power 
    unit_of_measurement: var
    precision: 2
    float: True
    state_class: measurement
    size: 2  

  L2 reactive Power:
    address: 2540
    title: L2 reactive Power 
    unit_of_measurement: var
    precision: 2
    float: True
    state_class: measurement
    size: 2  

  L3 reactive Power:
    address: 2542
    title: L3 reactive Power 
    unit_of_measurement: var
    precision: 2
    float: True
    state_class: measurement
    size: 2  

  Total reactive Power:
    address: 2544
    title: Total reactive Power 
    unit_of_measurement: vae
    precision: 2
    float: True
    state_class: measurement
    size: 2  
    
  Frequency:
    address: 2498
    title: Frequency 
    unit_of_measurement: Hz
    precision: 2
    float: True
    device_class: frequency
    state_class: measurement
    size: 2  
    
  L1 Power Factor:
    address: 2554
    title: L1 Power Factor 
    precision: 2
    float: True
    state_class: measurement
    size: 2
    
  L2 Power Factor:
    address: 2556
    title: L2 Power Factor 
    precision: 2
    float: True
    state_class: measurement
    size: 2
    
  L3 Power Factor:
    address: 2558
    title: L3 Power Factor 
    precision: 2
    float: True
    state_class: measurement
    size: 2
    
  Total Power Factor:
    address: 2560
    title: Total Power Factor 
    precision: 2
    float: True
    state_class: measurement
    size: 2
    
  Counter N1:
    address: 462
    title: Counter N1 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter N2:
    address: 464
    title: Counter N2 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter N3:
    address: 466
    title: Counter N3
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter N4:
    address: 468
    title: Counter N4 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C1:
    address: 470
    title: Counter C1 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C2:
    address: 472
    title: Counter C2
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C3:
    address: 474
    title: Counter C3 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C4:
    address: 476
    title: Counter C4 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C5:
    address: 478
    title: Counter C5 
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C6:
    address: 480
    title: Counter C6
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C7:
    address: 482
    title: Counter C7
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

  Counter C8:
    address: 484
    title: Counter C8
    unit_of_measurement: Wh
    precision: 3
    float: False
    device_class: energy
    state_class: total_increasing
    size: 2

**Comment by timlaing** [comment]
Your PR has now been merged. Thanks. :)
