### ISSUE TITLE
Support for Eastron SDM630

### ISSUE THREAD

**Issue by akuchenbuch** [timlaing/modbus_local_gateway#13]
Hello,
is it possible to integrate the Eastron SDM630 V2 as the most supported device?
I have a Waveshare RS485 TO POE ETH connected to an "Eastron SDM630 V2".
When I use the INtegration and select the "Eastron SDM230" as a device, the data of a phase is also displayed. Are there any plans or extensions to support the "Eastron SDM630 V2"?

**Comment by timlaing** [comment]
I am happy to take a look at this for you. I do not have this device. Would you be have to test a configuration file for me?

**Comment by Galileo77** [comment]
Hello
i can test this device to, i also use a Waveshare Modbus Gateway.

**Comment by timlaing** [comment]
This should be resolved in release v1.4.0
