### ISSUE TITLE
STATE_CLASS_TOTAL_INCREASING (new bug)

### ISSUE THREAD

**Issue by jojkopeter** [timlaing/modbus_local_gateway#14]
Hello,
Can you fix the error with an update?
The following can be seen in the HA log:

Logger: homeassistant.components.sensor.const
Source: helpers/deprecation.py:205
Integration: Sensor (documentation, issues)
First occurred: 16:28:50 (1 occurrences)
Last logged: 16:28:50

STATE_CLASS_TOTAL_INCREASING was used from modbus_local_gateway, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/timlaing/modbus_local_gateway

**Comment by timlaing** [comment]
This will be updated soon, thanks for letting me know.
