### ISSUE TITLE
How to make this work with a Growatt MOD 6000TL3-X

### ISSUE THREAD

**Issue by Sicos1977** [timlaing/modbus_local_gateway#21]
Hi,

I'm using a waveshare RS485 to eth that I can get connected to your integration. With the waveshare I want to read the settings from a Growatt Mod 6000TL3-X. Can you give me a hint about where to start to modify your integration so that this is also supported?

Greetings,
Kees

**Comment by Sicos1977** [comment]
I found this manual but have no idea about how to read this --> https://www.photovoltaicsolar.in/Growatt_Manual/MAX%20Series%20Modbus%20RTU%20Protocol.pdf

**Comment by timlaing** [comment]
This should be resolved in release v1.4.0
